import Head from 'next/head'
import Image from 'next/image'
import HomePage from '../components/full pages/HomePage'
import Header from '../components/Header/Header'
import Sidebar from '../components/Sidebar/Sidebar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title> Google Kepp </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
        <Sidebar/>
        <HomePage/>

      </main>
    </div>
  )
}
