import Head from 'next/head'
import Image from 'next/image'
import HomePage from '../components/full pages/HomePage'
import Header from '../components/Header/Header'
import Sidebar from '../components/Sidebar/Sidebar'


import { Wrapper } from "../components/Header/Header.styles"
import GlobalStyles from "../styles/globals"
import AuthRoute from '../components/AuthRoute/AuthRoute'

export default function Home() {
  return (
    <div>
      <GlobalStyles />
      <Head>
        <title> Google Kepp </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



        <Wrapper>
          <AuthRoute>
            <Header/>
            <Sidebar/>
            <HomePage/>
          </AuthRoute>
        </Wrapper>

    </div>
  )
}
